### PR TITLE
Use hex encoded keys to avoid confusion (see #37)

### PR DESCRIPTION
**Pull request by tuupola**

### CODE REVIEW

**Comment by tuupola** [comment]
@brycx Could you do a test run with one of your libraries which uses the `test_vectors.json` file?

**Comment by brycx** [comment]
Yeah, I'll do a run with the Rust implementation now.

**Comment by brycx** [comment]
Passing local and CI: https://github.com/return/branca/pull/25

**Comment by tuupola** [comment]
Thanks!

**Pull request merged**
